### PR TITLE
Fixes #54

### LINKED ISSUE #54: No matching method found: setReadFromSlaves for class org.redisson.config.ClusterServersConfig
<h2>Issue</h2>

**Component**: kafka-clj
**Version**: 4.0.0
**Issue**: Kafka consumer node creation fails with ``setReadFromSlaves`` method not found for class ``org.redisson.config.ClusterServersConfig``
**First hand review**: Current version of ``kafka-clj 4.0.0`` depends on ``redisson 3.2.2`` that does not have ``setReadFromSlaves`` method as per Javadoc- http://static.javadoc.io/org.redisson/redisson/3.2.2/org/redisson/config/ClusterServersConfig.html and the same has been removed as per this commit- https://github.com/redisson/redisson/commit/e258d827962f3d83fc23e4cb317fb286c7fb0978#diff-3094cc7afe686f997e19a467c3580094L84

<h2>Exception</h2>

```
Caused by: java.lang.IllegalArgumentException: No matching method found: setReadFromSlaves for class org.redisson.config.ClusterServersConfig
 at clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:53)
    clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:28)
    kafka_clj.redis.cluster$create_config.invokeStatic (cluster.clj:115)
    kafka_clj.redis.cluster$create_config.invoke (cluster.clj:98)
    kafka_clj.redis.cluster$connect.invokeStatic (cluster.clj:121)
    kafka_clj.redis.cluster$connect.invoke (cluster.clj:119)
    kafka_clj.redis.cluster$create.invokeStatic (cluster.clj:228)
    kafka_clj.redis.cluster$create.invoke (cluster.clj:226)
    kafka_clj.redis.core$redis_cluster_conn.invokeStatic (core.clj:63)
    kafka_clj.redis.core$redis_cluster_conn.invoke (core.clj:59)
    kafka_clj.redis.core$create_cluster_conn.invokeStatic (core.clj:75)
    kafka_clj.redis.core$create_cluster_conn.invoke (core.clj:74)
    kafka_clj.redis.core$create.invokeStatic (core.clj:98)
    kafka_clj.redis.core$create.invoke (core.clj:85)
    kafka_clj.consumer.work_organiser$create_organiser_BANG_.invokeStatic (work_organiser.clj:377)
    kafka_clj.consumer.work_organiser$create_organiser_BANG_.invoke (work_organiser.clj:366)
    kafka_clj.consumer.node$create_node_BANG_.invokeStatic (node.clj:145)
    kafka_clj.consumer.node$create_node_BANG_.doInvoke (node.clj:94)
```

### PR DESCRIPTION
**Pull request by anujsrc**
* Uses ``setReadMode`` instead of deprecated and removed method ``setReadFromSlaves``
* Fixes startup tests to just expect and exception instead of a specific type
* Fixes work organiser test to accept the right number of args for saved offset function

### CODE REVIEW

**Comment by gerritjvv** [comment]
thanks!

**Comment by anujsrc** [comment]
@gerritjvv - Thanks for accepting the PR. Will you be tagging a version for Clojars that I can pull-in?

**Comment by gerritjvv** [comment]
yes, I'll make a .1 release

**Comment by anujsrc** [comment]
Thanks @gerritjvv :+1:  - Pulled-in.

**Pull request merged**
